language: node_js
env: 
  - NODE_OPTIONS=--experimental-worker
  - CODECOV_TOKEN=f65ece69-8be4-4cd8-bb6f-c397d2dbc967
node_js:
  - "10"
script:
  - npm run test
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search