
module.exports = {

    // Wallet - core
    WCORE_SET_ASSETS: "WCORE_SET_ASSETS",         // displayable (safe, no privkey) wallet assets
    WCORE_SET_ASSETS_RAW: "WCORE_SET_ASSETS_RAW", // internal encrypted wallet raw assets (w/ sub-asset privkeys) 
    WCORE_SET_ADDRESS_FULL: "WCORE_SET_ADDRESS_FULL",
    WCORE_SET_ADDRESSES_FULL_MULTI: "WCORE_SET_ADDRESSES_FULL_MULTI",
    WCORE_SET_ENRICHED_TXS: "WCORE_SET_ENRICHED_TXS",
    WCORE_SET_ENRICHED_TXS_MULTI: "WCORE_SET_ENRICHED_TXS_MULTI",
    WCORE_PUSH_LOCAL_TX: "WCORE_PUSH_LOCAL_TX",

    // Wallet - core - fees v2
    WCORE_SET_UTXO_FEES: "WCORE_SET_UTXO_FEES",
    WCORE_SET_ETH_GAS_PRICES: "WCORE_SET_ETH_GAS_PRICES",

    // Wallet - client specific
    WCLIENT_SET_ASSETS_ERROR: "WCLIENT_SET_ASSETS_ERROR",
    WCLIENT_SET_SELECTED_ASSET: "WCLIENT_SET_SELECTED_ASSET",

}